### ISSUE TITLE
Date dans un format bizarre

### ISSUE THREAD

**Issue by Matthias-Codvelle-Prime** [Matthias-Codvelle-Prime/module-test-puppeteer#2]
Les **_dates de la liste de liens_** sont dans un **_format bizarre_**

**Comment by Matthias-Codvelle-Prime** [comment]
@Matthias-Codvelle-Prime pourriez-vous nous envoyé ce que vous percevez comme format "bizarre" ?

**Comment by jeanbaptistevilain** [comment]
Je suis en France et les dates sont habituellement au format JJ/MM/AAAA

**Comment by Matthias-Codvelle-Prime** [comment]
@jeanbaptistevilain C'est donc le format AAAA/JJ/MM que vous avez pu percevoir.
Je vais proposer à l'équipe d'indiquer les dates selon la timezone pour la prochaine mise à jour.
